/*
 * This source file was generated by the Gradle 'init' task
 */
package chessproject;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;

import javafx.application.Application;
import javafx.fxml.FXMLLoader;
import javafx.scene.Scene;
import javafx.stage.Stage;

public class App extends Application {

    @Override
    public void start(Stage primaryStage) throws IOException {
        Path path = Paths.get("C:\\Users\\smart\\OneDrive - Hochschule Heilbronn\\Dokumente\\VSCode\\ChessProject\\app\\src\\main\\resources\\BoardView.fxml");
        if(Files.exists(path)) System.out.println(path.getFileName());
        FXMLLoader fxmlLoader = new FXMLLoader(App.class.getResource("/BoardView.fxml"));
        Scene scene = new Scene(fxmlLoader.load());
        primaryStage.setTitle("Substitution decipher");
        primaryStage.setScene(scene);
        primaryStage.setResizable(false);
        primaryStage.show();
    }

    public static void main(String[] args) {
        launch(args);  // Launches the JavaFX application
    }
}
